version: "3"
tasks:
  trivy-scan:
    desc: Scan a Docker image for vulnerabilities using Trivy
    silent: true
    deps: [trivy-image]
    cmds:
      - docker run -v $(pwd):/app ghcr.io/open-containers/trivy-task:latest {{ .CLI_ARGS }}
  trivy-image:
    desc: Pull required Trivy image
    silent: true
    cmds:
      - docker pull ghcr.io/open-containers/trivy-task:latest
